### PR TITLE
Full Stack Automation

### PR DESCRIPTION
**Pull request by droidlabour**
We have automated the overall installation with individual Docker containers for ELK stack along with auto import of Kibana Dashboard and Visualisation, and along with Auto downloading/extracting AWS usage and billing reports from S3 and finally running the main.go code.

### CODE REVIEW

**Comment by ProTip** [comment]
Wow, this is an awesome pull request! Might take me a little bit to look over everything.

**Comment by sagarkar10** [comment]
Take your time! Glad you found it awesome.

**Comment by bdentino** [comment]
This is fantastic! Saved me so much time. I did have to adjust a few minor things to get this working with my account. I'm not sure if it's related to the fact that I have my billing reports stored under an extra prefix in my bucket (e.g. `reports-bucket/report-prefix/report-name/yyyymmdd-yyyymmdd...`), so I thought I should list it here in case someone else encounters the same issues:

- The documentation states that `S3_BILL_PATH_NAME` must start with a `/`, but the orchestration script couldn't find any of my billing files until I removed this leading slash
- The manifest file name wasn't properly constructed and so requests to download returned 404: 
```
latest_json_file_name = '/' + path_name_s3_billing + '/' + monthly_dir_name + path_name_s3_billing + '-Manifest.json'
``` 
needed to be 
```
latest_json_file_name = path_name_s3_billing + '/' + monthly_dir_name + '/' + folder_name_s3_billing + '-Manifest.json'
``` 
for me (where `folder_name_s3_billing = path_name_s3_billing.split('/')[-1]`)

I can submit a PR with these updates if necessary, just not really sure how specific these updates are to my particular setup

**Comment by sagarkar10** [comment]
@bdentino I guess the changes has already been made to the `orchestrate.py` file. May be you have a old version of the code. Happy to help. :)

**Comment by droidlabour** [comment]
@ProTip Any ETA about the merge?

**Comment by ProTip** [comment]
I'm going to trust that the work everyone has been putting into this has been a value add; the original project was pretty basic. I'd be interested in just handing this off to somebody interested. Unfortunately I no longer utilize this at work and don't really have the bandwidth to keep up with all the work being done..

**Comment by Rammmsankar** [comment]
Hi All , 
Is it required to change in elasticsearch with localhost as the url is elasticsearch:9200 , please guide

**Comment by droidlabour** [comment]
@Rammmsankar Can you please create an issue?

**Pull request merged**
